esphome:
  name: esphome-car-detector
  friendly_name: ultrasonic-control-garage-door

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: YOUR_KEY
ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

sensor:
  - platform: ultrasonic
    trigger_pin: GPIO27
    echo_pin: GPIO14
    name: "Car distance"
    update_interval: 5s
    timeout: 4.0m
    
